### ISSUE TITLE
Width/Height fields don't get updated by the dropdown menu

### ISSUE THREAD

**Issue by gnadenlos** [throttlekitty/SDXLCustomAspectRatio#1]
Don't know if this is intended behavior, but it would be better if the dropdown menu would update the width and height fields - otherwise you don't know if manual values or dropdown values are used.

**Comment by throttlekitty** [comment]
I couldn't easily work out how to not show the H/W values, they have no effect.

**Comment by stephantual** [comment]
Ths probably won't help, but note this is common to all nodes of this type. It may have to do with the way comfy allows to convert fields to widgets and vice versa,which in turn could lead to issues if users were trying to pass dyanimc data to those (as they would conflic with the drop down values)
